name: simple_yolo_example
description: Simple example demonstrating YOLO Flutter plugin camera lifecycle
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # YOLO plugin from parent directory
  ultralytics_yolo:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true